name: hadolint

on:
  pull_request:
    branches:
      - zebra-mining
  push:
    branches:
      - zebra-mining

jobs:
  hadolint:
    name: Lint Dockerfile
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run hadolint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile
          config: .hadolint.yaml
